services:
  # Backend API Service
  - type: web
    name: vaidya-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health

  # Frontend Static Site
  - type: static
    name: vaidya-frontend
    buildCommand: echo "No build needed"
    staticPublishPath: ./html-frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
