services:
  # Backend API Service
  - type: web
    name: vaidya-backend
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health

  # Frontend Static Site
  - type: static
    name: vaidya-frontend
    buildCommand: echo "No build needed"
    staticPublishPath: ./html-frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
